### ISSUE TITLE
Trying to understand an error message

### ISSUE THREAD

**Issue by karfau** [skymethod/kv-connect-kit#1]
I'm using this library at val.town: https://www.val.town/v/karfau/queuedJobs
and I'm getting the following error message that I don't understand:
```
Error: Unexpected trailing bytes: 256
    at checkEnd (https://raw.githubusercontent.com/skymethod/kv-connect-kit/v0.0.4/bytes.ts:5:26)
    at decodeV8 (https://raw.githubusercontent.com/skymethod/kv-connect-kit/v0.0.4/v8.ts:18:9)
    at decodeV8 (https://raw.githubusercontent.com/skymethod/kv-connect-kit/v0.0.4/client.ts:232:59)
    at readValue (https://raw.githubusercontent.com/skymethod/kv-connect-kit/v0.0.4/client.ts:191:38)
    at RemoteKv.listStream (https://raw.githubusercontent.com/skymethod/kv-connect-kit/v0.0.4/client.ts:423:35)
    at listStream.next (<anonymous>)
    at https://esm.town/v/karfau/queuedJobs?v=9:13:25
    at eventLoopTick (ext:core/01_core.js:183:11)
```

could you help me to understand how to debug that or what the reason for this could be?

**Comment by karfau** [comment]
Not relevant to me anymore
